# This is a basic workflow that is manually triggered

name: Build_Documents

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "greet"
  build-project:
    env:
      BASE_NAME: operatingsystem

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout project and transforms
        uses: actions/checkout@v2 
        with: 
          submodules: true
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Install lib
        run: sudo apt-get install -y xsltproc
      - name: Convert XML to HTML
        run: make
      - name: Install PDFifier
        if: ${{ github.event_name }} == workflow_dispatch
        run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
      - name: PDFify
        if: ${{ github.event_name }} == workflow_dispatch
        run: >
           xvfb-run -- /usr/bin/wkhtmltopdf \
            --javascript-delay 15000  \
            file://$(pwd)/output/${{ env.BASE_NAME }}-release.html?expand=on \
            ./output/${{ env.BASE_NAME }}-release.pdf;
      - name: Package it up
        run: cd output && zip -r ../${{ env.BASE_NAME }}.zip .
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ env.BASE_NAME }}.zip 
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          folder: output # The folder the action should deploy.

